export const CROWNEST_MCP_TOOLS = [
  "run_code",
  "get_agent_context",
  "run_command",
  "create_sandbox",
  "kill_sandbox",
  "write_file",
  "write_file_bytes",
  "read_file",
  "read_file_bytes",
  "get_file_download_url",
  "list_files",
  "download_artifact",
  "get_artifact_download_url",
  "list_sandboxes",
  "get_usage",
  "get_sandbox",
  "set_sandbox_ttl",
  "get_command",
  "cancel_command",
  "stream_command_logs",
  "delete_file",
  "move_file",
  "make_directory",
  "stat_file",
  "create_artifact",
  "list_artifacts",
  "get_artifact",
  "delete_artifact",
  "create_preview",
  "list_previews",
  "get_preview",
  "revoke_preview",
  "create_code_context",
  "list_code_contexts",
  "get_code_context",
  "delete_code_context",
  "list_api_keys",
  "get_api_key",
  "revoke_api_key",
  "create_project",
  "list_projects",
  "create_workspace_run",
  "upload_workspace_run_archive",
  "create_workspace_run_archive_transfer",
  "upload_workspace_run_archive_transfer",
  "finalize_workspace_run_archive",
  "start_workspace_run",
  "get_workspace_run",
  "list_workspace_runs",
  "replay_workspace_run_events",
  "cancel_workspace_run",
  "get_workspace_run_evidence",
] as const;

export const CROWNEST_MCP_PROMPTS = [
  "crownest_workspace_run",
  "crownest_sandbox_session",
] as const;

export const CROWNEST_MCP_RESOURCES = ["crownest://agent/context"] as const;
